// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

// Fallback values for development (Lasy preview)
const FALLBACK_SUPABASE_URL = "https://mtfhjdxsvlunaudrriro.supabase.co";
const FALLBACK_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10ZmhqZHhzdmx1bmF1ZHJyaXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjM0MzEsImV4cCI6MjA3MDA5OTQzMX0.PlmbyJ0jRsPVC4-vBZZ28-j2SegW0FXrQ4aHQ4hEBDU";

// Environment variables (for production deployment)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || FALLBACK_SUPABASE_ANON_KEY;

// Lazy-loaded Supabase client
let supabaseClient: SupabaseClient | null = null;

function getSupabase(): SupabaseClient {
  if (!supabaseClient) {
    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      throw new Error(
        'Missing Supabase environment variables. Please check your .env.local file.'
      );
    }
    
    supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        autoRefreshToken: true,
        persistSession: typeof window !== 'undefined', // Only persist in browser
      },
    });
  }
  
  return supabaseClient;
}

// Export both the function and a direct instance for convenience
export const supabase = getSupabase();
export { getSupabase };

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase";
// or
// import { getSupabase } from "@/lib/supabase";
// const supabase = getSupabase();